### ISSUE TITLE
Dynamically lookup modulepath instead of using static directory names

### ISSUE THREAD

**Issue by bzilla** [puppetlabs/puppetlabs-pe_quick_data#39]
In tasks/site-modules.sh, modules are being searched for using static paths and directory names:

line 66
`codeenv=$(ls -1 /etc/puppetlabs/code/environments)`

line 84
`        if [ ! -d "$envpath/site-modules/" ]`

Not all Puppet installations necessarily have or use a 'site-modules' directory.

Using `$(puppet config print modulepath)` might be a better method to determine where to look for modules, roles and profiles.

Parsing modulepath in environment.conf may also be a cleaner way to looks for modules in a given deployed environment. The list of directories could be generated something like this:

`for dir in $(grep modulepath environment.conf | awk '{print $3}' | sed "s/:/ /g" | sed "s/\$basemodulepath//"); do echo $dir; done`

The task at tasks/roles_and_profiles.sh similarly searches a static directory hierarchy and could benefit from a similar dynamic lookup.  The above improvements would ensure the collection of data is more complete and accurate.

**Comment by moedes** [comment]
Great suggestions for the module.  

With release version 2.1.0 we implemented;

Moved all module collection to the site module task and removed task roles_and_profiles

Moved to discovering modulepaths instead of assuming the path for better results

Made tasks hidden from task show and documentation to alleviate some confusion as to what to run for data collection

Started to use pe_quick_data.log to log information for troubleshooting and quick information on the site_modules task
